<?php

return [
    'tags' => [
        "feature",
        "bug",
        "enhancement",
        "documentation",
        "security",
        "new-feature",
        "optimization",
        "architecture",
        "workflow",
        "standardisation",
        "refactoring",
        "testing",
        "monitoring",
        "security-update",
        "documentation-update",
        "high-priority",
        "low-priority",
        "breaking-change",
        "non-breaking",
        "urgent",
        "minor-impact",
        "major-impact",
        "backward-compatible",
        "non-backward-compatible",
        "API-change",
        "UI-change",
        "backend",
        "frontend",
        "database",
        "microservices",
        "cloud",
        "devops",
        "infrastructure",
        "CI/CD",
        "data-model",
        "proposal",
        "approved",
        "in-progress",
        "review",
        "testing-phase",
        "deployed",
        "archived",
        "authentication",
        "authorization",
        "data-privacy",
        "performance",
        "accessibility",
        "usability",
        "scalability",
        "internationalization",
        "localization",
        "design-pattern",
        "best-practice",
        "technical-debt",
        "proof-of-concept",
        "legacy-support",
        "process-improvement",
        "legal",
        "compliance",
        "GDPR",
        "ISO-27001",
        "PCI-DSS",
        "developer-experience",
        "user-experience",
        "cross-functional",
        "internal-only",
        "external-facing",
        "client-request",
    ],
    'sections' => [
        ['name' => 'motivation', 'label' => 'Motivation', 'default' => true],
        ['name' => 'proposal', 'label' => 'Proposal', 'default' => true],
        ['name' => 'impactAnalysis', 'label' => 'Impact Analysis', 'default' => true],
        ['name' => 'implementationPlan', 'label' => 'Implementation Plan', 'default' => true],
        ['name' => 'designConstraints', 'label' => 'Design Constraints', 'default' => false],
        ['name' => 'alternativesConsidered', 'label' => 'Alternatives Considered', 'default' => false],
        ['name' => 'securityConsiderations', 'label' => 'Security Considerations', 'default' => false],
        ['name' => 'performanceConsiderations', 'label' => 'Performance Considerations', 'default' => false],
        ['name' => 'testingStrategy', 'label' => 'Testing Strategy', 'default' => false],
        ['name' => 'deploymentPlan', 'label' => 'Deployment Plan', 'default' => false],
        ['name' => 'compatibility', 'label' => 'Compatibility', 'default' => false],
        ['name' => 'dependencies', 'label' => 'Dependencies', 'default' => false],
        ['name' => 'operationalImpact', 'label' => 'Operational Impact', 'default' => false],
        ['name' => 'complianceAndLegal', 'label' => 'Compliance and Legal', 'default' => false],
        ['name' => 'resourcesRequired', 'label' => 'Resources Required', 'default' => false],
        ['name' => 'endUserDocumentation', 'label' => 'End-User Documentation', 'default' => false],
        ['name' => 'references', 'label' => 'References', 'default' => false],
    ],
];
